title: Humus_altro
baseURL: /
params:
  description: A vanilla theme for Stackbit
  header:
    title: ''
    has_nav: false
    nav_links:
      - label: Home
        url: /
      - label: Generic
        url: /generic/
      - label: Elements
        url: /elements/
      - label: Ipsum
        url: /ipsum/
      - label: lorem-ipsum
        url: lorem-ipsum
        new_window: false
        type: action
  footer:
    content: ''
    links: []
    has_social: true
    social_links:
      - label: Facebook
        url: 'https://www.facebook.com/humusaltro'
        new_window: true
      - label: Instagram
        url: 'https://www.instagram.com/humus_altro/'
        new_window: true
      - label: DEV
        url: 'https://dev.to/'
        new_window: true
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
