title: 'Humus'
baseURL: /
params:
  description: ''
  header:
    title: 'Scendi in profondità con gli ipertesti'
    subtitle: 'Clicca il pulsante _ALTRO'
    logo_url: '/images/logo-bianco.png'
    has_nav: false
    nav_links:
      - label: Home
        url: /
  footer:
    content: ''
    links: []
    has_social: true
    social_links:
      - label: Facebook
        url: 'https://www.facebook.com/humusaltro'
        new_window: true
      - label: Instagram
        url: 'https://www.instagram.com/humus_altro/'
        new_window: true
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
